print("this is second")
print("this is after rebase")
print("this is third line")
print("this is fourth line")
print("this is fifth line")
print("This is the commit to reset to")
print("This is stashed")
print("this is before rebase")
print("this is after branched out")
